---
- hosts: localhost
  tasks:
    - name: purge the test keypair
      openstack.cloud.keypair:
        name: test_keypair
        state: absent
    - name: purge the test server
      openstack.cloud.server:
        name: test_vm
        state: absent
    - name: purge the volume disk
      openstack.cloud.volume:
        name: test_vol
        state: absent
    - name: purge the image
      openstack.cloud.image:
        name: test_img
        state: absent
    - name: Clean up the temp image
      file:
        path: "{{ item }}" 
        state: absent
      with_fileglob:
        - '/var/lib/virt-lightning/pool/upstream/*_exp.qcow2'
    - name: Clean up the local temp dir
      file:
        path: images/basehost
        state: absent
    - name: Clean up the basehost
      virt_lightning.virt_lightning.vm:
        name: basehost
        state: absent
    - name: Clean up the temp VM
      virt_lightning.virt_lightning.vm:
        name: newvm
        state: absent

