---
- hosts: localhost
  tasks:
    - name: Purge the openstack project
      ansible.builtin.include_role:
        name: purge

    - name: Clean up the temp image
      with_fileglob:
        - /var/lib/virt-lightning/pool/upstream/*_exp.qcow2
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent

    - name: Clean up the local temp dir
      ansible.builtin.file:
        path: images/basehost
        state: absent

    - name: Clean up the basehost
      virt_lightning.virt_lightning.vm:
        name: basehost
        state: absent
    - name: Clean up the temp VM
      virt_lightning.virt_lightning.vm:
        name: newvm
        state: absent
