---
- hosts: localhost
  gather_facts: false
  tasks:
    - include_role:
        name: purge

- hosts: localhost
  tasks:
    - include_role:
        name: deploy
      vars:
        deploy__config_drive: false
    - include_role:
        name: test_vm
    - name: purge the test server
      openstack.cloud.server:
        name: test_vm
        state: absent

- hosts: localhost
  tasks:
    - include_role:
        name: deploy
      vars:
        deploy__config_drive: true
    - include_role:
        name: test_vm
    - name: purge the test server
      openstack.cloud.server:
        name: test_vm
        state: absent

- hosts: localhost
  gather_facts: false
  tasks:
    - include_role:
        name: purge
