---
- hosts: localhost
  gather_facts: false
  tasks:
    - ansible.builtin.include_role:
        name: purge

- hosts: localhost
  tasks:
    - vars:
        deploy__config_drive: false
      ansible.builtin.include_role:
        name: deploy

    - ansible.builtin.include_role:
        name: test_vm

    - name: purge the test server
      openstack.cloud.server:
        name: test_vm
        state: absent

- hosts: localhost
  tasks:
    - vars:
        deploy__config_drive: true
      ansible.builtin.include_role:
        name: deploy

    - include_role:
        name: test_vm
    - name: purge the test server
      openstack.cloud.server:
        name: test_vm
        state: absent

- hosts: localhost
  gather_facts: false
  tasks:
    - include_role:
        name: purge
