---
- hosts: localhost
  vars:
    www_dir: /var/www/bsd-cloud-image.org/images
    dest_dir: "{{ www_dir }}/{{ image_os }}/{{ image_version }}"
    qcow2_swift_path: images/{{ image_os }}/{{ image_version}}/{{ ansible_date_time.date }}/{{ root_fs }}/{{ final_name }}-{{ ansible_date_time.date }}.qcow2
    yaml_swift_path: images/{{ image_os }}/{{ image_version}}/{{ ansible_date_time.date }}/{{ root_fs }}/{{ final_name }}-{{ ansible_date_time.date }}.yaml
  tasks:
    - become: true
      ansible.builtin.file:
        path: "{{ dest_dir }}"
        state: directory
        recurse: true

    - name: Promote the new image Virt-Lightning (1/4)
      become: true
      ansible.builtin.command: mv /var/lib/virt-lightning/pool/upstream/{{ final_name }}_exp.qcow2 {{ dest_dir }}/{{ final_name }}.qcow2

    - name: Promote the new image Virt-Lightning (yaml) (2/4)
      become: true
      ansible.builtin.command: mv /var/lib/virt-lightning/pool/upstream/{{ final_name }}_exp.yaml {{ dest_dir }}/{{ final_name }}.yaml

    - name: Promote the new image Virt-Lightning (3/4)
      become: true
      ansible.builtin.command: cp {{ dest_dir }}/{{ final_name }}.qcow2 /var/lib/virt-lightning/pool/upstream/{{ final_name }}.qcow2

    - name: Promote the new image Virt-Lightning (yaml) (4/4)
      become: true
      ansible.builtin.command: cp {{ dest_dir }}/{{ final_name }}.yaml /var/lib/virt-lightning/pool/upstream/{{ final_name }}.yaml

    - name: Fix the ownership of the target dir Virt-Lightning
      become: true
      ansible.builtin.file:
        path: "{{ dest_dir }}"
        state: directory
        recurse: true
        owner: goneri
        group: goneri

    - name: upload the qcow2 file
      openstack.cloud.object:
        container: bsd-cloud-image.org
        name: "{{ qcow2_swift_path }}"
        filename: /var/lib/virt-lightning/pool/upstream/{{ final_name }}.qcow2
      register: result
      until: result is not failed
      retries: 3

    - name: upload the YAML file
      openstack.cloud.object:
        container: bsd-cloud-image.org
        name: "{{ yaml_swift_path }}"
        filename: /var/lib/virt-lightning/pool/upstream/{{ final_name }}.yaml
      register: result
      until: result is not failed
      retries: 3

    - ansible.builtin.debug:
        msg: "Image availabe at: https://object-storage.public.mtl1.vexxhost.net/swift/v1/1dbafeefbd4f4c80864414a441e72dd2/bsd-cloud-image.org/{{ qcow2_swift_path
          }}"
